// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NADeviceListBody
    {
        /// <summary>
        /// Initializes a new instance of the NADeviceListBody class.
        /// </summary>
        public NADeviceListBody()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NADeviceListBody class.
        /// </summary>
        public NADeviceListBody(IList<NADevice> devices = default(IList<NADevice>), IList<NAModule> modules = default(IList<NAModule>))
        {
            Devices = devices;
            Modules = modules;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "devices")]
        public IList<NADevice> Devices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modules")]
        public IList<NAModule> Modules { get; set; }

    }
}
