// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAHouseModel
    {
        /// <summary>
        /// Initializes a new instance of the NAHouseModel class.
        /// </summary>
        public NAHouseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAHouseModel class.
        /// </summary>
        public NAHouseModel(string algoType = default(string), NAHouseModelCa ca = default(NAHouseModelCa), IDictionary<string, int?> extTemps = default(IDictionary<string, int?>), bool? firstAnticipateAvail = default(bool?), bool? firstPidAvail = default(bool?), NAStation gefs = default(NAStation), string inUse = default(string), NADate lastComputeTry = default(NADate), NALinkStation linkStation = default(NALinkStation), NAPidAlgo pidAlgo = default(NAPidAlgo), NAStation station = default(NAStation), string preferedAlgoType = default(string), NASimpleAlgo simpleAlgo = default(NASimpleAlgo), NADate time = default(NADate), bool? stationFirsttimeAnticipate = default(bool?), int? timeAlgoChanged = default(int?), int? timePidComputed = default(int?))
        {
            AlgoType = algoType;
            Ca = ca;
            ExtTemps = extTemps;
            FirstAnticipateAvail = firstAnticipateAvail;
            FirstPidAvail = firstPidAvail;
            Gefs = gefs;
            InUse = inUse;
            LastComputeTry = lastComputeTry;
            LinkStation = linkStation;
            PidAlgo = pidAlgo;
            Station = station;
            PreferedAlgoType = preferedAlgoType;
            SimpleAlgo = simpleAlgo;
            Time = time;
            StationFirsttimeAnticipate = stationFirsttimeAnticipate;
            TimeAlgoChanged = timeAlgoChanged;
            TimePidComputed = timePidComputed;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "algo_type")]
        public string AlgoType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ca")]
        public NAHouseModelCa Ca { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ext_temps")]
        public IDictionary<string, int?> ExtTemps { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "first_anticipate_avail")]
        public bool? FirstAnticipateAvail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "first_pid_avail")]
        public bool? FirstPidAvail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gefs")]
        public NAStation Gefs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "in_use")]
        public string InUse { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last_compute_try")]
        public NADate LastComputeTry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "link_station")]
        public NALinkStation LinkStation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pid_algo")]
        public NAPidAlgo PidAlgo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "station")]
        public NAStation Station { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prefered_algo_type")]
        public string PreferedAlgoType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "simple_algo")]
        public NASimpleAlgo SimpleAlgo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public NADate Time { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "station_firsttime_anticipate")]
        public bool? StationFirsttimeAnticipate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time_algo_changed")]
        public int? TimeAlgoChanged { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time_pid_computed")]
        public int? TimePidComputed { get; set; }

    }
}
