// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NALinkStation
    {
        /// <summary>
        /// Initializes a new instance of the NALinkStation class.
        /// </summary>
        public NALinkStation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NALinkStation class.
        /// </summary>
        public NALinkStation(string mac = default(string), string ext = default(string), double? temperature = default(double?))
        {
            Mac = mac;
            Ext = ext;
            Temperature = temperature;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mac")]
        public string Mac { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ext")]
        public string Ext { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Temperature")]
        public double? Temperature { get; set; }

    }
}
