// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAMeasure
    {
        /// <summary>
        /// Initializes a new instance of the NAMeasure class.
        /// </summary>
        public NAMeasure()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAMeasure class.
        /// </summary>
        public NAMeasure(IDictionary<string, IList<double?>> res = default(IDictionary<string, IList<double?>>), IList<string> type = default(IList<string>), double? rain60min = default(double?), double? rain24h = default(double?), double? rainLive = default(double?), long? rainUtc = default(long?), double? windStrength = default(double?), double? windAngle = default(double?), double? gustStrength = default(double?), double? gustAngle = default(double?), long? windTimeutc = default(long?))
        {
            Res = res;
            Type = type;
            Rain60min = rain60min;
            Rain24h = rain24h;
            RainLive = rainLive;
            RainUtc = rainUtc;
            WindStrength = windStrength;
            WindAngle = windAngle;
            GustStrength = gustStrength;
            GustAngle = gustAngle;
            WindTimeutc = windTimeutc;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "res")]
        public IDictionary<string, IList<double?>> Res { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public IList<string> Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rain_60min")]
        public double? Rain60min { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rain_24h")]
        public double? Rain24h { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rain_live")]
        public double? RainLive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rain_utc")]
        public long? RainUtc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "wind_strength")]
        public double? WindStrength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "wind_angle")]
        public double? WindAngle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gust_strength")]
        public double? GustStrength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gust_angle")]
        public double? GustAngle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "wind_timeutc")]
        public long? WindTimeutc { get; set; }

    }
}
