// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAMeasureBodyElem
    {
        /// <summary>
        /// Initializes a new instance of the NAMeasureBodyElem class.
        /// </summary>
        public NAMeasureBodyElem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAMeasureBodyElem class.
        /// </summary>
        public NAMeasureBodyElem(int? begTime = default(int?), int? stepTime = default(int?), IList<IList<double?>> value = default(IList<IList<double?>>))
        {
            BegTime = begTime;
            StepTime = stepTime;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "beg_time")]
        public int? BegTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "step_time")]
        public int? StepTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<IList<double?>> Value { get; set; }

    }
}
