// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NANewScheduleBody
    {
        /// <summary>
        /// Initializes a new instance of the NANewScheduleBody class.
        /// </summary>
        public NANewScheduleBody()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NANewScheduleBody class.
        /// </summary>
        /// <param name="scheduleId">Id of the schedule. It can be use with the
        /// method "switchschedule"
        /// </param>
        public NANewScheduleBody(string scheduleId = default(string))
        {
            ScheduleId = scheduleId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the schedule. It can be use with the method
        /// "switchschedule"
        ///
        /// </summary>
        [JsonProperty(PropertyName = "schedule_id")]
        public string ScheduleId { get; set; }

    }
}
