// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAObject
    {
        /// <summary>
        /// Initializes a new instance of the NAObject class.
        /// </summary>
        public NAObject()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAObject class.
        /// </summary>
        public NAObject(string id = default(string))
        {
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "$id")]
        public string Id { get; set; }

    }
}
