// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAOkResponse
    {
        /// <summary>
        /// Initializes a new instance of the NAOkResponse class.
        /// </summary>
        public NAOkResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAOkResponse class.
        /// </summary>
        public NAOkResponse(string status = default(string), double? timeExec = default(double?), int? timeServer = default(int?), string body = default(string))
        {
            Status = status;
            TimeExec = timeExec;
            TimeServer = timeServer;
            Body = body;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time_exec")]
        public double? TimeExec { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time_server")]
        public int? TimeServer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

    }
}
