// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NASetpointLog
    {
        /// <summary>
        /// Initializes a new instance of the NASetpointLog class.
        /// </summary>
        public NASetpointLog()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NASetpointLog class.
        /// </summary>
        public NASetpointLog(NASetpoint setpoint = default(NASetpoint), long? timestamp = default(long?))
        {
            Setpoint = setpoint;
            Timestamp = timestamp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "setpoint")]
        public NASetpoint Setpoint { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public long? Timestamp { get; set; }

    }
}
