// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAStationModule
    {
        /// <summary>
        /// Initializes a new instance of the NAStationModule class.
        /// </summary>
        public NAStationModule()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAStationModule class.
        /// </summary>
        /// <param name="type">Included in every device or module. It defines
        /// the type of the device/module. Its values are among :
        /// NAMain : for the base station
        /// NAModule1 : for the outdoor module
        /// NAModule4 : for the additionnal indoor module
        /// NAModule3 : for the rain gauge module
        /// NAPlug : for the thermostat relay/plug
        /// NATherm1 : for the thermostat module
        /// </param>
        /// <param name="dashboardData">It contains all the measurements that
        /// can be displayed on the dashboard</param>
        /// <param name="batteryVp">It contains the current battery status. The
        /// threshold depends on the kind of module, below is the list of the
        /// different threshold to take into account according the module type.
        /// "Indoor module Battery range: 6000 ... 4200" |
        /// INDOOR_BATTERY_LEVEL_FULL = 5640
        /// INDOOR_BATTERY_LEVEL_HIGH = 5280
        /// INDOOR_BATTERY_LEVEL_MEDIUM = 4920
        /// INDOOR_BATTERY_LEVEL_LOW = 4560
        /// "Below 4560: very low" |
        ///
        /// "Raingauge and outdoor module Battery range: 6000 ... 3600" |
        /// BATTERY_LEVEL_FULL = 5500
        /// BATTERY_LEVEL_HIGH = 5000
        /// BATTERY_LEVEL_MEDIUM = 4500
        /// BATTERY_LEVEL_LOW = 4000
        /// "Below 4000: very low" |
        ///
        /// "Thermostat Battery range: 4500 ... 3000" |
        /// THERMOSTAT_BATTERY_LEVEL_FULL = 4100
        /// THERMOSTAT_BATTERY_LEVEL_HIGH = 3600
        /// THERMOSTAT_BATTERY_LEVEL_MEDIUM = 3300
        /// THERMOSTAT_BATTERY_LEVEL_LOW = 3000
        /// "Below 3000: very low"
        /// </param>
        /// <param name="batteryPercent">It contains the current battery level
        /// in percentage.</param>
        /// <param name="rfStatus">"It contains the current radio status. The
        /// different thresholds to take into account are :" |
        /// RADIO_THRESHOLD_SIGNAL_LOW = 90
        /// RADIO_THRESHOLD_SIGNAL_MEDIUM = 80
        /// RADIO_THRESHOLD_SIGNAL_HIGH = 70
        /// RADIO_THRESHOLD_SIGNAL_FULL = 60
        /// </param>
        public NAStationModule(string _id = default(string), string type = default(string), int? lastMessage = default(int?), int? lastSeen = default(int?), NADashboardData dashboardData = default(NADashboardData), IList<string> dataType = default(IList<string>), string moduleName = default(string), int? lastSetup = default(int?), int? batteryVp = default(int?), int? batteryPercent = default(int?), int? rfStatus = default(int?), int? firmware = default(int?))
        {
            this._id = _id;
            Type = type;
            LastMessage = lastMessage;
            LastSeen = lastSeen;
            DashboardData = dashboardData;
            DataType = dataType;
            ModuleName = moduleName;
            LastSetup = lastSetup;
            BatteryVp = batteryVp;
            BatteryPercent = batteryPercent;
            RfStatus = rfStatus;
            Firmware = firmware;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_id")]
        public string _id { get; set; }

        /// <summary>
        /// Gets or sets included in every device or module. It defines the
        /// type of the device/module. Its values are among :
        /// NAMain : for the base station
        /// NAModule1 : for the outdoor module
        /// NAModule4 : for the additionnal indoor module
        /// NAModule3 : for the rain gauge module
        /// NAPlug : for the thermostat relay/plug
        /// NATherm1 : for the thermostat module
        ///
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last_message")]
        public int? LastMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last_seen")]
        public int? LastSeen { get; set; }

        /// <summary>
        /// Gets or sets it contains all the measurements that can be displayed
        /// on the dashboard
        /// </summary>
        [JsonProperty(PropertyName = "dashboard_data")]
        public NADashboardData DashboardData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data_type")]
        public IList<string> DataType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "module_name")]
        public string ModuleName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last_setup")]
        public int? LastSetup { get; set; }

        /// <summary>
        /// Gets or sets it contains the current battery status. The threshold
        /// depends on the kind of module, below is the list of the different
        /// threshold to take into account according the module type.
        /// "Indoor module Battery range: 6000 ... 4200" |
        /// INDOOR_BATTERY_LEVEL_FULL = 5640
        /// INDOOR_BATTERY_LEVEL_HIGH = 5280
        /// INDOOR_BATTERY_LEVEL_MEDIUM = 4920
        /// INDOOR_BATTERY_LEVEL_LOW = 4560
        /// "Below 4560: very low" |
        ///
        /// "Raingauge and outdoor module Battery range: 6000 ... 3600" |
        /// BATTERY_LEVEL_FULL = 5500
        /// BATTERY_LEVEL_HIGH = 5000
        /// BATTERY_LEVEL_MEDIUM = 4500
        /// BATTERY_LEVEL_LOW = 4000
        /// "Below 4000: very low" |
        ///
        /// "Thermostat Battery range: 4500 ... 3000" |
        /// THERMOSTAT_BATTERY_LEVEL_FULL = 4100
        /// THERMOSTAT_BATTERY_LEVEL_HIGH = 3600
        /// THERMOSTAT_BATTERY_LEVEL_MEDIUM = 3300
        /// THERMOSTAT_BATTERY_LEVEL_LOW = 3000
        /// "Below 3000: very low"
        ///
        /// </summary>
        [JsonProperty(PropertyName = "battery_vp")]
        public int? BatteryVp { get; set; }

        /// <summary>
        /// Gets or sets it contains the current battery level in percentage.
        /// </summary>
        [JsonProperty(PropertyName = "battery_percent")]
        public int? BatteryPercent { get; set; }

        /// <summary>
        /// Gets or sets "It contains the current radio status. The different
        /// thresholds to take into account are :" |
        /// RADIO_THRESHOLD_SIGNAL_LOW = 90
        /// RADIO_THRESHOLD_SIGNAL_MEDIUM = 80
        /// RADIO_THRESHOLD_SIGNAL_HIGH = 70
        /// RADIO_THRESHOLD_SIGNAL_FULL = 60
        ///
        /// </summary>
        [JsonProperty(PropertyName = "rf_status")]
        public int? RfStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firmware")]
        public int? Firmware { get; set; }

    }
}
