// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAStation
    {
        /// <summary>
        /// Initializes a new instance of the NAStation class.
        /// </summary>
        public NAStation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAStation class.
        /// </summary>
        public NAStation(int? lagDown = default(int?), int? lagUp = default(int?), double? offOvershoot = default(double?), double? onOvershoot = default(double?), int? pk = default(int?), int? tau = default(int?))
        {
            LagDown = lagDown;
            LagUp = lagUp;
            OffOvershoot = offOvershoot;
            OnOvershoot = onOvershoot;
            Pk = pk;
            Tau = tau;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lag_down")]
        public int? LagDown { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lag_up")]
        public int? LagUp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "off_overshoot")]
        public double? OffOvershoot { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "on_overshoot")]
        public double? OnOvershoot { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pk")]
        public int? Pk { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tau")]
        public int? Tau { get; set; }

    }
}
