// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAThermMeasure
    {
        /// <summary>
        /// Initializes a new instance of the NAThermMeasure class.
        /// </summary>
        public NAThermMeasure()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAThermMeasure class.
        /// </summary>
        public NAThermMeasure(int? time = default(int?), double? temperature = default(double?), double? setpointTemp = default(double?))
        {
            Time = time;
            Temperature = temperature;
            SetpointTemp = setpointTemp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public int? Time { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "temperature")]
        public double? Temperature { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "setpoint_temp")]
        public double? SetpointTemp { get; set; }

    }
}
