// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAThermProgram
    {
        /// <summary>
        /// Initializes a new instance of the NAThermProgram class.
        /// </summary>
        public NAThermProgram()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAThermProgram class.
        /// </summary>
        public NAThermProgram(string programId = default(string), string name = default(string), IList<NAZone> zones = default(IList<NAZone>), IList<NATimeTableItem> timetable = default(IList<NATimeTableItem>), bool? selected = default(bool?))
        {
            ProgramId = programId;
            Name = name;
            Zones = zones;
            Timetable = timetable;
            Selected = selected;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "program_id")]
        public string ProgramId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zones")]
        public IList<NAZone> Zones { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timetable")]
        public IList<NATimeTableItem> Timetable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "selected")]
        public bool? Selected { get; set; }

    }
}
