// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAUser
    {
        /// <summary>
        /// Initializes a new instance of the NAUser class.
        /// </summary>
        public NAUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAUser class.
        /// </summary>
        /// <param name="administrative">Contains administrative information
        /// related to the user</param>
        /// <param name="devices">An array of string containing the ids of the
        /// devices owned by the user</param>
        /// <param name="friendDevices">An array of string containing the ids
        /// of the devices on which the user has a "guest" access
        /// </param>
        public NAUser(string _id = default(string), NAUserAdministrative administrative = default(NAUserAdministrative), NADate dateCreation = default(NADate), IList<string> devices = default(IList<string>), IList<string> friendDevices = default(IList<string>), string mail = default(string), int? timelineNotRead = default(int?), int? timelineSize = default(int?))
        {
            this._id = _id;
            Administrative = administrative;
            DateCreation = dateCreation;
            Devices = devices;
            FriendDevices = friendDevices;
            Mail = mail;
            TimelineNotRead = timelineNotRead;
            TimelineSize = timelineSize;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_id")]
        public string _id { get; set; }

        /// <summary>
        /// Gets or sets contains administrative information related to the
        /// user
        /// </summary>
        [JsonProperty(PropertyName = "administrative")]
        public NAUserAdministrative Administrative { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date_creation")]
        public NADate DateCreation { get; set; }

        /// <summary>
        /// Gets or sets an array of string containing the ids of the devices
        /// owned by the user
        /// </summary>
        [JsonProperty(PropertyName = "devices")]
        public IList<string> Devices { get; set; }

        /// <summary>
        /// Gets or sets an array of string containing the ids of the devices
        /// on which the user has a "guest" access
        ///
        /// </summary>
        [JsonProperty(PropertyName = "friend_devices")]
        public IList<string> FriendDevices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mail")]
        public string Mail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeline_not_read")]
        public int? TimelineNotRead { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeline_size")]
        public int? TimelineSize { get; set; }

    }
}
