// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAWelcomeHomeData
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeHomeData class.
        /// </summary>
        public NAWelcomeHomeData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeHomeData class.
        /// </summary>
        public NAWelcomeHomeData(IList<NAWelcomeHome> homes = default(IList<NAWelcomeHome>), NAWelcomeUser user = default(NAWelcomeUser), NAWelcomeGlobalInfo globalInfo = default(NAWelcomeGlobalInfo))
        {
            Homes = homes;
            User = user;
            GlobalInfo = globalInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "homes")]
        public IList<NAWelcomeHome> Homes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public NAWelcomeUser User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "global_info")]
        public NAWelcomeGlobalInfo GlobalInfo { get; set; }

    }
}
