// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAWelcomePlace
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomePlace class.
        /// </summary>
        public NAWelcomePlace()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomePlace class.
        /// </summary>
        /// <param name="city">City of the home.</param>
        /// <param name="country">Country of the home.</param>
        /// <param name="timezone">Timezone of the home.</param>
        public NAWelcomePlace(string city = default(string), string country = default(string), string timezone = default(string))
        {
            City = city;
            Country = country;
            Timezone = timezone;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets city of the home.
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets country of the home.
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public string Country { get; set; }

        /// <summary>
        /// Gets or sets timezone of the home.
        /// </summary>
        [JsonProperty(PropertyName = "timezone")]
        public string Timezone { get; set; }

    }
}
