// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAWelcomeSnapshot
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeSnapshot class.
        /// </summary>
        public NAWelcomeSnapshot()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeSnapshot class.
        /// </summary>
        /// <param name="id">Id of the snapshot.</param>
        /// <param name="version">Version of the snapshot.</param>
        /// <param name="key">Key for this snapshot.</param>
        public NAWelcomeSnapshot(string id = default(string), int? version = default(int?), string key = default(string))
        {
            Id = id;
            Version = version;
            Key = key;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the snapshot.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets version of the snapshot.
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public int? Version { get; set; }

        /// <summary>
        /// Gets or sets key for this snapshot.
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

    }
}
