// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAWelcomeUser
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeUser class.
        /// </summary>
        public NAWelcomeUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeUser class.
        /// </summary>
        /// <param name="lang">user locale</param>
        /// <param name="regLocale">user regional preferences (used for
        /// displaying date)</param>
        public NAWelcomeUser(string lang = default(string), string regLocale = default(string))
        {
            Lang = lang;
            RegLocale = regLocale;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets user locale
        /// </summary>
        [JsonProperty(PropertyName = "lang")]
        public string Lang { get; set; }

        /// <summary>
        /// Gets or sets user regional preferences (used for displaying date)
        /// </summary>
        [JsonProperty(PropertyName = "reg_locale")]
        public string RegLocale { get; set; }

    }
}
