// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAWelcomeModule
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeModule class.
        /// </summary>
        public NAWelcomeModule()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeModule class.
        /// </summary>
        /// <param name="id">mac address of the module</param>
        /// <param name="type">NACamDoorTag for tags</param>
        /// <param name="name">name of the module (given by the user)</param>
        /// <param name="batteryPercent">remaining battery percentage</param>
        /// <param name="status">status of the module</param>
        /// <param name="rf">Radio status</param>
        /// <param name="lastActivity">Timestamp of last move detected by the
        /// module</param>
        public NAWelcomeModule(string id = default(string), string type = default(string), string name = default(string), int? batteryPercent = default(int?), string status = default(string), string rf = default(string), int? lastActivity = default(int?))
        {
            Id = id;
            Type = type;
            Name = name;
            BatteryPercent = batteryPercent;
            Status = status;
            Rf = rf;
            LastActivity = lastActivity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets mac address of the module
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets nACamDoorTag for tags
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets name of the module (given by the user)
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets remaining battery percentage
        /// </summary>
        [JsonProperty(PropertyName = "battery_percent")]
        public int? BatteryPercent { get; set; }

        /// <summary>
        /// Gets or sets status of the module
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets radio status
        /// </summary>
        [JsonProperty(PropertyName = "rf")]
        public string Rf { get; set; }

        /// <summary>
        /// Gets or sets timestamp of last move detected by the module
        /// </summary>
        [JsonProperty(PropertyName = "last_activity")]
        public int? LastActivity { get; set; }

    }
}
