// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAWelcomeEventData
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeEventData class.
        /// </summary>
        public NAWelcomeEventData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeEventData class.
        /// </summary>
        public NAWelcomeEventData(IList<NAWelcomeEvent> eventsList = default(IList<NAWelcomeEvent>))
        {
            EventsList = eventsList;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "events_list")]
        public IList<NAWelcomeEvent> EventsList { get; set; }

    }
}
