// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAWelcomeGlobalInfo
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeGlobalInfo class.
        /// </summary>
        public NAWelcomeGlobalInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeGlobalInfo class.
        /// </summary>
        /// <param name="showTags">show tags</param>
        public NAWelcomeGlobalInfo(bool? showTags = default(bool?))
        {
            ShowTags = showTags;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets show tags
        /// </summary>
        [JsonProperty(PropertyName = "show_tags")]
        public bool? ShowTags { get; set; }

    }
}
