// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAWelcomeEvent
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeEvent class.
        /// </summary>
        public NAWelcomeEvent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeEvent class.
        /// </summary>
        /// <param name="id">Identifier of the event</param>
        /// <param name="type">Type of events. Go to the Welcome page for
        /// further details.</param>
        /// <param name="time">Time of occurence of event</param>
        /// <param name="cameraId">Camera that detected the event</param>
        /// <param name="personId">Id of the person the event is about (if
        /// any)</param>
        /// <param name="snapshot">Snapshot id, version and key. (Used in
        /// Getcamerapicture)</param>
        /// <param name="videoId">Identifier of the video</param>
        /// <param name="videoStatus">Status of the video (recording, deleted
        /// or available)</param>
        /// <param name="isArrival">If person was considered away before being
        /// seen during this event</param>
        /// <param name="message">User facing event description</param>
        /// <param name="subType">Subtypes of SD and Alim events. Go to Welcome
        /// page for further details.</param>
        public NAWelcomeEvent(string id = default(string), string type = default(string), int? time = default(int?), string cameraId = default(string), string personId = default(string), NAWelcomeSnapshot snapshot = default(NAWelcomeSnapshot), string videoId = default(string), string videoStatus = default(string), bool? isArrival = default(bool?), string message = default(string), int? subType = default(int?))
        {
            Id = id;
            Type = type;
            Time = time;
            CameraId = cameraId;
            PersonId = personId;
            Snapshot = snapshot;
            VideoId = videoId;
            VideoStatus = videoStatus;
            IsArrival = isArrival;
            Message = message;
            SubType = subType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets identifier of the event
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets type of events. Go to the Welcome page for further
        /// details.
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets time of occurence of event
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public int? Time { get; set; }

        /// <summary>
        /// Gets or sets camera that detected the event
        /// </summary>
        [JsonProperty(PropertyName = "camera_id")]
        public string CameraId { get; set; }

        /// <summary>
        /// Gets or sets id of the person the event is about (if any)
        /// </summary>
        [JsonProperty(PropertyName = "person_id")]
        public string PersonId { get; set; }

        /// <summary>
        /// Gets or sets snapshot id, version and key. (Used in
        /// Getcamerapicture)
        /// </summary>
        [JsonProperty(PropertyName = "snapshot")]
        public NAWelcomeSnapshot Snapshot { get; set; }

        /// <summary>
        /// Gets or sets identifier of the video
        /// </summary>
        [JsonProperty(PropertyName = "video_id")]
        public string VideoId { get; set; }

        /// <summary>
        /// Gets or sets status of the video (recording, deleted or available)
        /// </summary>
        [JsonProperty(PropertyName = "video_status")]
        public string VideoStatus { get; set; }

        /// <summary>
        /// Gets or sets if person was considered away before being seen during
        /// this event
        /// </summary>
        [JsonProperty(PropertyName = "is_arrival")]
        public bool? IsArrival { get; set; }

        /// <summary>
        /// Gets or sets user facing event description
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets subtypes of SD and Alim events. Go to Welcome page for
        /// further details.
        /// </summary>
        [JsonProperty(PropertyName = "sub_type")]
        public int? SubType { get; set; }

    }
}
