// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAWelcomePerson
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomePerson class.
        /// </summary>
        public NAWelcomePerson()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomePerson class.
        /// </summary>
        /// <param name="id">Id of the person.</param>
        /// <param name="lastSeen">Time at which the person was last
        /// seen.</param>
        /// <param name="outOfSight">True if the Person is out of
        /// sight.</param>
        /// <param name="pseudo">Name of the person, if pseudo is missing,
        /// person is unknown.</param>
        public NAWelcomePerson(string id = default(string), int? lastSeen = default(int?), bool? outOfSight = default(bool?), NAWelcomeFace face = default(NAWelcomeFace), string pseudo = default(string))
        {
            Id = id;
            LastSeen = lastSeen;
            OutOfSight = outOfSight;
            Face = face;
            Pseudo = pseudo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the person.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets time at which the person was last seen.
        /// </summary>
        [JsonProperty(PropertyName = "last_seen")]
        public int? LastSeen { get; set; }

        /// <summary>
        /// Gets or sets true if the Person is out of sight.
        /// </summary>
        [JsonProperty(PropertyName = "out_of_sight")]
        public bool? OutOfSight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "face")]
        public NAWelcomeFace Face { get; set; }

        /// <summary>
        /// Gets or sets name of the person, if pseudo is missing, person is
        /// unknown.
        /// </summary>
        [JsonProperty(PropertyName = "pseudo")]
        public string Pseudo { get; set; }

    }
}
