// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NAWelcomeHome
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeHome class.
        /// </summary>
        public NAWelcomeHome()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeHome class.
        /// </summary>
        /// <param name="id">Id of the home.</param>
        /// <param name="name">Name of the home</param>
        public NAWelcomeHome(string id = default(string), string name = default(string), IList<NAWelcomePerson> persons = default(IList<NAWelcomePerson>), NAWelcomePlace place = default(NAWelcomePlace), IList<NAWelcomeCamera> cameras = default(IList<NAWelcomeCamera>), IList<NAWelcomeEvent> events = default(IList<NAWelcomeEvent>), IList<NAWelcomeModule> modules = default(IList<NAWelcomeModule>))
        {
            Id = id;
            Name = name;
            Persons = persons;
            Place = place;
            Cameras = cameras;
            Events = events;
            Modules = modules;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the home.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets name of the home
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "persons")]
        public IList<NAWelcomePerson> Persons { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "place")]
        public NAWelcomePlace Place { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cameras")]
        public IList<NAWelcomeCamera> Cameras { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "events")]
        public IList<NAWelcomeEvent> Events { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modules")]
        public IList<NAWelcomeModule> Modules { get; set; }

    }
}
