// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace netatmocore.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NAWelcomeFace
    {
        /// <summary>
        /// Initializes a new instance of the NAWelcomeFace class.
        /// </summary>
        public NAWelcomeFace()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NAWelcomeFace class.
        /// </summary>
        /// <param name="id">Id of the face.</param>
        /// <param name="version">Version of the face if user changed their
        /// photo.</param>
        /// <param name="key">Key for this face to use in
        /// getcamerapicture.</param>
        public NAWelcomeFace(string id = default(string), int? version = default(int?), string key = default(string))
        {
            Id = id;
            Version = version;
            Key = key;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the face.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets version of the face if user changed their photo.
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public int? Version { get; set; }

        /// <summary>
        /// Gets or sets key for this face to use in getcamerapicture.
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

    }
}
