// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart.Helpers.DB;
using Smart.Web.Models;

namespace Smart.Web.Migrations
{
    [DbContext(typeof(PowerContext))]
    [Migration("20181221034156_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Smart.Web.Models.PowerReading", b =>
                {
                    b.Property<int>("PowerReadingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DailyKilowattHours");

                    b.Property<double>("KilowattHours");

                    b.Property<DateTime>("MeasureTime");

                    b.HasKey("PowerReadingId");

                    b.ToTable("PowerReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
