version: '2.4'
services:
  influxdb:
    image: "influxdb:1.8.6"
    #mem_limit: 2048m
    #memswap_limit: 2048m
    #command: tail -F anything
    ports:
    - "8086:8086"
    volumes:
    - /data/influx2:/var/lib/influxdb 
    restart: always
    environment:
    - INFLUXDB_LOGGING_LEVEL=warn
    - INFLUXDB_DATA_INDEX_VERSION=tsi1
    - INFLUXDB_DATA_MAX_CONCURRENT_COMPACTIONS=1
    - INFLUXDB_DATA_COMPACT_THROUGHPUT=12m
    - INFLUXDB_DATA_COMPACT_THROUGHPUT_BURST=12m
    - INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE=512m
    - INFLUXDB_DATA_CACHE_SNAPSHOT_MEMORY_SIZE=12m
