version: '2'
services:
  mqttserver:
    image: "eclipse-mosquitto"
    restart: always
    hostname: mqttserver
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
    - eclipse-mosquitto
  influxdb:
    image: "arm32v7/influxdb"
    ports:
    - "8086:8086"
    volumes:
    - /data/smart/influx2:/var/lib/influxdb 
  grafana:
    image: "grafana/grafana"
    environment: 
    - GF_INSTALL_PLUGINS=fetzerch-sunandmoon-datasource
    ports:
    - "3000:3000"
    depends_on: 
    - influxdb
    volumes:
    - /data/smart/grafana:/var/lib/grafana 
  mqttclient:
    build: 
      context: ../src/Client
      dockerfile: Dockerfile
    environment:
    - MQTT_SERVER_ADDRESS=mqttserver
    - INFLUX_SERVER_ADDRESS=influxdb
    env_file: .env    
    restart: always
    depends_on: 
    - mqttserver
    - influxdb