version: '3'
services:
  apiserver:
    image: "jakkaj/smartmeterapi"
    ports:
     - "5000:5000"
    env_file:
    - /Users/jak/Scripts/.env
  mqttserver:
    image: "eclipse-mosquitto"
    hostname: mqttserver
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
    - eclipse-mosquitto
  mqttclient:
    depends_on: 
    - mqttserver
    - apiserver
    image: "jakkaj/smartmetermqttclient"