version: '3'
services:
  mqttserver:
    image: "eclipse-mosquitto"
    restart: always
    hostname: mqttserver
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
    - eclipse-mosquitto
  influxdb:
    image: "influxdb"
    ports:
    - "8086:8086"
    volumes:
    - /data/influx:/var/lib/influxdb 
  grafana:
    image: "grafana/grafana"
    ports:
    - "3000:3000"
    depends_on: 
    - influxdb
    volumes:
    - /data/grafana:/var/lib/grafana 
  # mqttclient:
  #   environment:
  #   - MQTT_SERVER_ADDRESS=mqttserver
  #   - INFLUX_SERVER_ADDRESS=influxdb
  #   env_file: .env    
  #   restart: always
  #   depends_on: 
  #   - mqttserver
  #   - influxdb
  #   image: "jakkaj/smartmetermqttclient"