version: '2.4'
services:
  clipsal:    
    restart: always
    build: 
      context: ../src/Clipsal 
      dockerfile: Dockerfile    
    ports:
    - 3005:3005
    env_file: .env_clipsal
  amber:    
    restart: always
    build: 
      context: ../src/Amber 
      dockerfile: Dockerfile    
    ports:
    - 3004:3004
    env_file: .env
  tesla:    
    restart: always
    build: 
      context: ../src/Tesla
      dockerfile: Dockerfile    
    ports:
    - 5061:5001
  modbus:
    volumes:
      - /etc/localtime:/etc/localtime
    restart: always
    build: 
      context: ../src/Modbus
      dockerfile: Dockerfile    
    ports:
    - 5060:5000
  mqttserver:
    image: "eclipse-mosquitto"
    restart: always
    hostname: mqttserver
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
    - eclipse-mosquitto
  influxdb:    
    image: "arm32v7/influxdb"
    ports:
    - "8086:8086"
    volumes:
    - /data/influx2:/var/lib/influxdb 
    restart: always
    environment:
    - INFLUXDB_LOGGING_LEVEL=warn
    - INFLUXDB_DATA_INDEX_VERSION=tsi1 
    - INFLUXDB_DATA_CACHE_SNAPSHOT_MEMORY_SIZE=12m
  grafana:
    image: "grafana/grafana"
    environment: 
    - GF_INSTALL_PLUGINS=fetzerch-sunandmoon-datasource
    ports:
    - "3000:3000"
    depends_on: 
    - influxdb
    volumes:
    - /data/grafana:/var/lib/grafana 
    restart: always
  mqttclient:
    build: 
      context: ../src/Client
      dockerfile: Dockerfile
    environment:
    - MQTT_SERVER_ADDRESS=mqttserver
    - INFLUX_SERVER_ADDRESS=influxdb
    env_file: .env    
    restart: always
    depends_on: 
    - mqttserver
    - influxdb
    
