#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:  
  docker-in-docker:
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile    
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro # does not work on Windows! Will need to generate in container :(
      # Forwarding the socket is optional, but lets docker work inside the container if you install the Docker CLI.
      # See the docker-in-docker-compose definition for details on how to install it.
      - /var/run/docker.sock:/var/run/docker.sock 
      - ~/data/influxrestore:/var/lib/influxdb #to assist with downloading and expanding the influx database
    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity 
    env_file:
    - .env
    environment:
    - INFLUX_SERVER_ADDRESS=influxdbrestore
  
  influxdbrestore:
    image: "influxdb:1.8.1"
    ports:
    - "8086:8087"
    volumes:
    - ~/data/influxrestore:/var/lib/influxdb   